version: "3.7"

services:
  gpt:
    container_name: humanbios-ai
    image: humanbios-ai
    restart: unless-stopped
    volumes:
    - ./models:/app/usr/src/models

networks:
  default:
    external:
      name: caddynet
